"use client";
import axios from "axios";

const InsertDataPage = () => {
  const handleInsertData = async () => {
    const jsonData = [
      {
        name: "Assault Intercessors",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/intercess.jpg",
        faction: "Space Marines",
        link: "https://www.warhammer.com/en-US/shop/Assault-Intercessors-2020",
      },
      {
        name: "Terminator Captain",
        price: 0,
        edition: 10,
        image: "/images/figurine-image/10thtermiecapt.jpg",
        faction: "Space Marines",
        link: "https://www.warhammer.com/en-US/home",
      },
      {
        name: "Titus",
        price: 0,
        edition: 10,
        image: "/images/figurine-image/titus.jpg",
        faction: "Space Marines",
        link: "https://www.warhammer.com/en-US/home",
      },
      {
        name: "Company Heroes",
        price: 65,
        edition: 10,
        image: "/images/figurine-image/coheroes.jpg",
        faction: "Space Marines",
        link: "https://www.warhammer.com/en-US/shop/space-marines-company-heroes-2023",
      },
      {
        name: "Terminator Squad",
        price: 65,
        edition: 10,
        image: "/images/figurine-image/termies.jpg",
        faction: "Space Marines",
        link: "https://www.warhammer.com/en-US/shop/space-marines-terminator-squad-2023",
      },
      {
        name: "Terminator Assault Squad",
        price: 60,
        edition: 10,
        image: "/images/figurine-image/termieassault.jpg",
        faction: "Space Marines",
        link: "https://www.warhammer.com/en-US/shop/Space-Marine-Terminator-Close-Combat%20Squad-2020?slug=shop&slug=Space-Marine-Terminator-Close-Combat+Squad-2020",
      },
      {
        name: "Sterngaurd Veterans",
        price: 60,
        edition: 10,
        image: "/images/figurine-image/sterngaurdvet.jpg",
        faction: "Space Marines",
        link: "https://www.warhammer.com/en-US/shop/space-marines-sternguard-veteran-squad-2023",
      },
      {
        name: "Jump Pack Intercessors",
        price: 60,
        edition: 10,
        image: "/images/figurine-image/jumpyinters.jpg",
        faction: "Space Marines",
        link: "https://www.warhammer.com/en-US/shop/space-marines-jump-pack-intercessors-2023",
      },
      {
        name: "Jump Pack Captain",
        price: 40,
        edition: 10,
        image: "/images/figurine-image/packcapt.jpg",
        faction: "Space Marines",
        link: "https://www.warhammer.com/en-US/shop/space-marines-captain-with-jump-pack-2023",
      },
      {
        name: "Terminator Chaplain",
        price: 42,
        edition: 10,
        image: "/images/figurine-image/termiechap.jpg",
        faction: "Space Marines",
        link: "https://www.warhammer.com/en-US/shop/space-marines-chaplain-in-terminator-armour-2023?slug=shop&slug=space-marines-chaplain-in-terminator-armour-2023",
      },
      {
        name: "Morvenn Vahl",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/morvenn.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/Morvenn-Vahl-Abbess-Sanctorum-2021",
      },
      {
        name: "Palatine",
        price: 35,
        edition: 9,
        image: "/images/figurine-image/palatine.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/Adepta-Sororitas-Palatine-2021",
      },
      {
        name: "Aestred Thurga",
        price: 40,
        edition: 9,
        image: "/images/figurine-image/aestred.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/Aestred-Thurga-Relinquant-At-Arms",
      },
      {
        name: "Sister Dogmata",
        price: 35,
        edition: 9,
        image: "/images/figurine-image/dogmata.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/Adepta-Sororitas-Sister-Dogmata-2021",
      },
      {
        name: "Celestian Sacrestants",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/sacrestants.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/Adepta-Sororitas-Celestian-Sacresants-2021",
      },
      {
        name: "Paragon Warsuits",
        price: 75,
        edition: 9,
        image: "/images/figurine-image/pgwarsuit.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/Adepta-Sororitas-Paragon-Warsuit-2021",
      },
      {
        name: "Castigator Battle Tank",
        price: 90,
        edition: 9,
        image: "/images/figurine-image/castigator.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/Adepta-Sororitas-Castigator",
      },
      {
        name: "Kill Team Novitiates",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/novitiates.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/kill-team-novitiates-2022",
      },
      {
        name: "Blade Champion",
        price: 40,
        edition: 9,
        image: "/images/figurine-image/bladechamp.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/adeptus-custodes-blade-champion-2022",
      },
      {
        name: "Sydonian Skatros",
        price: 38,
        edition: 10,
        image: "/images/figurine-image/skatros.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/adeptus-mechanicus-sydonian-skatros-2023",
      },
      {
        name: "Skitarii Marshall",
        price: 35,
        edition: 9,
        image: "/images/figurine-image/skitmarsh.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/Adeptus-Mechanicus-Skitarii-Marshall-2021",
      },
      {
        name: "Commisar",
        price: 35,
        edition: 9,
        image: "/images/figurine-image/commisar.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/astra-militarum-commissar-2023",
      },
      {
        name: "Minka Lesk",
        price: 21,
        edition: 9,
        image: "/images/figurine-image/minka.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/minka-lesk-the-last-whiteshield-omnibus-pb-eng-2023?slug=shop&slug=minka-lesk-the-last-whiteshield-omnibus-pb-eng-2023",
      },
      {
        name: "Kasrkin Kill Team",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/kasrkin.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/kill-team-kasrkin-2023",
      },
      {
        name: "Cadian Command Squad",
        price: 45,
        edition: 9,
        image: "/images/figurine-image/cadiancommsq.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/astra-militarum-cadian-command-squad-2023",
      },
      {
        name: "Cadian Shock Troops",
        price: 50,
        edition: 9,
        image: "/images/figurine-image/cadianshock.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/astra-militarum-cadian-shock-troops-2023",
      },
      {
        name: "Armored Sentinel",
        price: 45,
        edition: 9,
        image: "/images/figurine-image/armsent.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/astra-militarum-armoured-sentinel-2023",
      },
      {
        name: "Scout Sentinel",
        price: 45,
        edition: 9,
        image: "/images/figurine-image/scoutsent.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/astra-militarum-scout-sentinel-2023",
      },
      {
        name: "Ursula Creed",
        price: 45,
        edition: 9,
        image: "/images/figurine-image/ursula.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/astra-militarum-lord-castellan-ursula-creed-2023",
      },
      {
        name: "Heavy Weapons Squad",
        price: 50,
        edition: 9,
        image: "/images/figurine-image/heavywepsq.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/astra-militarum-cadian-heavy-weapons-squad-2023",
      },
      {
        name: "Cadian Castellan",
        price: 35,
        edition: 9,
        image: "/images/figurine-image/castellan.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/astra-militarum-cadian-castellan-2023",
      },
      {
        name: "Attilan Rough Riders",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/attilanriders.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/astra-militarum-attilan-rough-riders-2023",
      },
      {
        name: "Rogal Dorn Battle Tank",
        price: 100,
        edition: 9,
        image: "/images/figurine-image/rogdortank.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/astra-militarum-rogal-dorn-battle-tank-2023",
      },
      {
        name: "Lord Solar Leontus",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/leontus.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/astra-militarum-lord-solar-leontus-2023",
      },
      {
        name: "Vindicare Assassin",
        price: 40,
        edition: 9,
        image: "/images/figurine-image/vindicare.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/Vindicare-Assassin?slug=shop&slug=Vindicare-Assassin",
      },
      {
        name: "Imperial Navy Breachers",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/navbreach.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/kill-team-imperial-navy-breachers-2023",
      },
      {
        name: "Exaction Squad",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/extrsq.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/kill-team-exaction-squad-2023",
      },
      {
        name: "Inquisitorial Agents",
        price: 55,
        edition: 9,
        image: "/images/figurine-image/inqagent.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/kill-team-inquisitorial-agents-2023",
      },
      {
        name: "Armiger Warglaives",
        price: 90,
        edition: 8,
        image: "/images/figurine-image/warglaive.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/imperial-knights-knight-armigers-armiger-warglaive-2022",
      },
      {
        name: "Armiger Helverins",
        price: 90,
        edition: 8,
        image: "/images/figurine-image/helverin.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/imperial-knights-knight-armigers-armiger-helverin-2022",
      },
      {
        name: "Knight Castellan",
        price: 185,
        edition: 8,
        image: "/images/figurine-image/knightcastellan.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/imperial-knights-knight-dominus-knight-castellan-2022",
      },
      {
        name: "Knight Valiant",
        price: 185,
        edition: 8,
        image: "/images/figurine-image/knightvaliant.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/imperial-knights-knight-dominus-knight-valiant-2022",
      },
      {
        name: "Knight Preceptor",
        price: 170,
        edition: 8,
        image: "/images/figurine-image/knightpreceptor.jpg",
        faction: "Imperium Armies",
        link: "https://www.warhammer.com/en-US/shop/knight-preceptor-2022",
      },
      {
        name: "Kill Team: Legionaries",
        price: 70,
        edition: 9,
        image: "/images/figurine-image/legionaries.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/kill-team-legionaries-2022",
      },
      {
        name: "Chaos Chosen",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/chaoschosen.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/slaves-to-darkness-chaos-chosen-2023",
      },
      {
        name: "Warpsmith",
        price: 40,
        edition: 9,
        image: "/images/figurine-image/warpsmith.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/chaos-space-marines-warpsmith-2022",
      },
      {
        name: "Daemon Prince",
        price: 80,
        edition: 9,
        image: "/images/figurine-image/daemonprince.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/slaves-to-darkness-daemon-prince-2023?slug=shop&slug=slaves-to-darkness-daemon-prince-2023",
      },
      {
        name: "Possessed",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/possessed.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/chaos-space-marines-possessed-2022",
      },
      {
        name: "Chaos Cultists",
        price: 50,
        edition: 9,
        image: "/images/figurine-image/chaoscult.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/chaos-space-marines-chaos-cultists-2022",
      },
      {
        name: "Dark Commune",
        price: 55,
        edition: 9,
        image: "/images/figurine-image/dkcomm.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/chaos-space-marines-dark-commune-2022",
      },
      {
        name: "Accursed Cultists",
        price: 55,
        edition: 9,
        image: "/images/figurine-image/acccult.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/chaos-space-marines-accursed-cultists-2022",
      },
      {
        name: "Blooded Kill Team",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/bloodkillteam.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/kill-team-blooded-2022",
      },
      {
        name: "Lord of Virulence",
        price: 40,
        edition: 9,
        image: "/images/figurine-image/lordvirulence.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/Death-Guard-Lord-of-Virulence-2020",
      },
      {
        name: "Plague Marines",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/plaguemar.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/Death-Guard-Plague-Marines-2020",
      },
      {
        name: "Lord Felthius and The Tainted Cohort",
        price: 45,
        edition: 9,
        image: "/images/figurine-image/lordfelthius.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/Lord-Felthius-And-The-Tainted-Cohort-2021",
      },
      {
        name: "Infernal Master",
        price: 40,
        edition: 9,
        image: "/images/figurine-image/infernalmas.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/thousand-sons-infernal-master-2022",
      },
      {
        name: "Azrakh the Annihilator",
        price: 38,
        edition: 9,
        image: "/images/figurine-image/azrakh.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/world-eater-azrakh-the-annihilator-2022",
      },
      {
        name: "Angron Daemon Primarch",
        price: 170,
        edition: 9,
        image: "/images/figurine-image/angron.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/world-eaters-angron-daemon-primarch-of-khorne-2023",
      },
      {
        name: "Khorne Berzerkers",
        price: 65,
        edition: 9,
        image: "/images/figurine-image/kbzerk.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/world-eaters-khorne-berserkers-2023",
      },
      {
        name: "Lord Invocatus",
        price: 65,
        edition: 9,
        image: "/images/figurine-image/invocatus.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/world-eaters-lord-invocatus-2023",
      },
      {
        name: "Chaos Lord on Daemonic Mount",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/chaosmount.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/slaves-to-darkness-chaos-lord-on-daemonic-mount-2023",
      },
      {
        name: "Eightbounds",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/eightbound.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/world-eaters-eightbound-2023",
      },
      {
        name: "Exalted Eightbounds",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/exeightbound.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/world-eaters-exalted-eightbound-2023?slug=shop&slug=world-eaters-exalted-eightbound-2023",
      },
      {
        name: "Jakhals",
        price: 55,
        edition: 9,
        image: "/images/figurine-image/jakhals.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/world-eaters-jakhals-2023",
      },
      {
        name: "Be'lakor, The Dark Master",
        price: 160,
        edition: 9,
        image: "/images/figurine-image/belakor.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/Chaos-Daemons-Belakor-The-Dark-Master-2021",
      },
      {
        name: "Vashtorr The Arkifane",
        price: 100,
        edition: 9,
        image: "/images/figurine-image/vashtorr.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/chaos-space-marines-vashtorr-the-arkifane-2023",
      },
      {
        name: "Knight Abominant",
        price: 185,
        edition: 9,
        image: "/images/figurine-image/knightabominant.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/chaos-knights-knight-abominant-2022",
      },
      {
        name: "War Dog Karnivores",
        price: 90,
        edition: 9,
        image: "/images/figurine-image/wardogkarn.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/chaos-knights-war-dog-karnivore-2022",
      },
      {
        name: "War Dog Stalkers",
        price: 90,
        edition: 9,
        image: "/images/figurine-image/wardogstalk.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/chaos-knights-war-dog-stalker-2022",
      },
      {
        name: "war dog brigands",
        price: 90,
        edition: 9,
        image: "/images/figurine-image/wardogbrig.jpg",
        faction: "Chaos",
        link: "https://www.warhammer.com/en-US/shop/chaos-knights-war-dog-brigand-2022",
      },
      {
        name: "Striking Scorpions",
        price: 50,
        edition: 10,
        image: "/images/figurine-image/strikscorp.jpg",
        faction: "Aeldari",
        link: "https://www.warhammer.com/en-US/shop/Eldar-Striking-Scorpions",
      },
      {
        name: "Lelith Hesperax",
        price: 45,
        edition: 9,
        image: "/images/figurine-image/lelith.jpg",
        faction: "Aeldari",
        link: "https://www.warhammer.com/en-US/shop/Drukhari-Lelith-Hesperax-2021",
      },
      {
        name: "Harlequin Troupe",
        price: 45,
        edition: 7,
        image: "/images/figurine-image/harletroup.jpg",
        faction: "Aeldari",
        link: "https://www.warhammer.com/en-US/shop/Harlequin-Troupe-Troop-2017",
      },
      {
        name: "Harlequin Solitaire",
        price: 32,
        edition: 7,
        image: "/images/figurine-image/harlsol.jpg",
        faction: "Aeldari",
        link: "https://www.warhammer.com/en-US/shop/Solitaire",
      },
      {
        name: "Skyweavers",
        price: 55,
        edition: 7,
        image: "/images/figurine-image/skyweavers.jpg",
        faction: "Aeldari",
        link: "https://www.warhammer.com/en-US/shop/Harlequin-Skyweavers",
      },
      {
        name: "Starweaver",
        price: 45,
        edition: 7,
        image: "/images/figurine-image/starweavers.jpg",
        faction: "Aeldari",
        link: "https://www.warhammer.com/en-US/shop/Harlequin-Starweaver?slug=shop&slug=Harlequin-Starweaver",
      },
      {
        name: "Voidweaver",
        price: 45,
        edition: 7,
        image: "/images/figurine-image/voidweavers.jpg",
        faction: "Aeldari",
        link: "https://www.warhammer.com/en-US/shop/Voidweaver",
      },
      {
        name: "Death Jester",
        price: 33.5,
        edition: 7,
        image: "/images/figurine-image/deathjester.jpg",
        faction: "Aeldari",
        link: "https://www.warhammer.com/en-US/shop/Harlequin-Death-Jester",
      },
      {
        name: "Harlequin Shadowseer",
        price: 33.5,
        edition: 7,
        image: "/images/figurine-image/shadowseer.jpg",
        faction: "Aeldari",
        link: "https://www.warhammer.com/en-US/shop/Harlequin-Shadowseer",
      },
      {
        name: "Reductus Saboteur",
        price: 35,
        edition: 9,
        image: "/images/figurine-image/reductus.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/genestealer-cults-reductus-saboteur-2022",
      },
      {
        name: "Einhyr Champion",
        price: 40,
        edition: 10,
        image: "/images/figurine-image/einhyr.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/lov-einhyr-champion-2022",
      },
      {
        name: "Emotekh The Stormlord",
        price: 45,
        edition: 10,
        image: "/images/figurine-image/emotekh.jpg",
        faction: "Necron",
        link: "https://www.warhammer.com/en-US/shop/necrons-imotekh-the-stormlord-2023",
      },
      {
        name: "Overlord with Translocation Shroud",
        price: 38,
        edition: 10,
        image: "/images/figurine-image/transoverlord.jpg",
        faction: "Necron",
        link: "https://www.warhammer.com/en-US/shop/necrons-overlord-and-translocation-shroud-2023",
      },
      {
        name: "Orikan The Diviner",
        price: 45,
        edition: 10,
        image: "/images/figurine-image/orikan.jpg",
        faction: "Necron",
        link: "https://www.warhammer.com/en-US/shop/necrons-orikan-the-diviner-2023",
      },
      {
        name: "Flayed Ones",
        price: 55,
        edition: 9,
        image: "/images/figurine-image/flayedone.jpg",
        faction: "Necron",
        link: "https://www.warhammer.com/en-US/shop/Necrons-Flayed-Ones-2021",
      },
      {
        name: "Chronomancer",
        price: 40,
        edition: 9,
        image: "/images/figurine-image/chrono.jpg",
        faction: "Necron",
        link: "https://www.warhammer.com/en-US/shop/Necrons-Chronomancer-2021",
      },
      {
        name: "Szarekh, The Silent King",
        price: 170,
        edition: 9,
        image: "/images/figurine-image/szarek.jpg",
        faction: "Necron",
        link: "https://www.warhammer.com/en-US/shop/Szarekh-The-Silent-King-2020",
      },
      {
        name: "C'tan Shard of The Void Dragon",
        price: 125,
        edition: 9,
        image: "/images/figurine-image/voidshard.jpg",
        faction: "Necron",
        link: "https://www.warhammer.com/en-US/shop/CTan-Shard-of-the-Void-Dragon-2020",
      },
      {
        name: "Monolith",
        price: 185,
        edition: 9,
        image: "/images/figurine-image/monolith.jpg",
        faction: "Necron",
        link: "https://www.warhammer.com/en-US/shop/Monolith-2020?slug=shop&slug=Monolith-2020",
      },
      {
        name: "Canoptek Doomstalker",
        price: 50,
        edition: 9,
        image: "/images/figurine-image/doomstalker.jpg",
        faction: "Necron",
        link: "https://www.warhammer.com/en-US/shop/Canoptek-Doomstalker-2020",
      },
      {
        name: "Hexmark Destoryer",
        price: 35,
        edition: 9,
        image: "/images/figurine-image/hexmark.jpg",
        faction: "Necron",
        link: "https://www.warhammer.com/en-US/shop/Hexmark-Destroyer-2020",
      },
      {
        name: "Ophidian Destroyers",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/ophidian.jpg",
        faction: "Necron",
        link: "https://www.warhammer.com/en-US/shop/Ophydian-Destroyers-2020",
      },
      {
        name: "Psychomancer",
        price: 35,
        edition: 9,
        image: "/images/figurine-image/psychomancer.jpg",
        faction: "Necron",
        link: "https://www.warhammer.com/en-US/shop/Necrons-Psychomancer-2020",
      },
      {
        name: "Lokhust Heavy Destroyer",
        price: 35,
        edition: 9,
        image: "/images/figurine-image/lokhust.jpg",
        faction: "Necron",
        link: "https://www.warhammer.com/en-US/shop/Lokhust-Heavy-Destroyer-2020",
      },
      {
        name: "Boss Snikrot",
        price: 40,
        edition: 9,
        image: "/images/figurine-image/snikrot.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/orks-boss-snikrot-2023",
      },
      {
        name: "Ethereal",
        price: 35,
        edition: 9,
        image: "/images/figurine-image/ethereal.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/tau-empire-ethereal-2022",
      },
      {
        name: "Pathfinders Kill Team",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/pathfinders.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/kill-team-tau-empire-pathfinders-2022",
      },
      {
        name: "Farstalker Kinband",
        price: 60,
        edition: 9,
        image: "/images/figurine-image/farstalker.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/kill-team-farstalker-kinband-2023",
      },
      {
        name: "Hormagaunts",
        price: 50,
        edition: 10,
        image: "/images/figurine-image/horma.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/tyranids-hormagaunts-2023",
      },
      {
        name: "Genestealers",
        price: 55,
        edition: 10,
        image: "/images/figurine-image/gene.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/tyranids-genestealers-2023",
      },
      {
        name: "Lictor",
        price: 50,
        edition: 10,
        image: "/images/figurine-image/lictor.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/tyranids-lictor-2023",
      },
      {
        name: "Nuerolictor",
        price: 40,
        edition: 10,
        image: "/images/figurine-image/nuelic.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/tyranids-neurolictor-2023",
      },
      {
        name: "Deathleaper",
        price: 60,
        edition: 10,
        image: "/images/figurine-image/deathleap.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/tyranids-deathleaper-2023",
      },
      {
        name: "Biovore",
        price: 50,
        edition: 10,
        image: "/images/figurine-image/biovore.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/tyranids-biovore-2023?slug=shop&slug=tyranids-biovore-2023",
      },
      {
        name: "Pyrovore",
        price: 50,
        edition: 10,
        image: "/images/figurine-image/pyrovore.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/tyranids-pyrovore-2023",
      },
      {
        name: "Norn Emissary",
        price: 115,
        edition: 10,
        image: "/images/figurine-image/nornem.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/tyranids-norn-emissary-2023",
      },
      {
        name: "Norn Assimilator",
        price: 115,
        edition: 10,
        image: "/images/figurine-image/nornas.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/tyranids-norn-assimilator-2023",
      },
      {
        name: "Termagants",
        price: 45,
        edition: 10,
        image: "/images/figurine-image/termagaunts.jpg",
        faction: "Xenos",
        link: "https://www.warhammer.com/en-US/shop/tyranids-termagants-2023",
      },
    ];
    try {
      await axios.post("/api/insert", jsonData);
    } catch (error) {
      console.error("Error occurred while inserting data:", error);
    }
  };

  return (
    <div>
      <button onClick={handleInsertData}>Insert Data</button>
    </div>
  );
};

export default InsertDataPage;
